-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "cubic_meter" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "linear_meter" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "material_border" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "material_cut" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "square_meter" DOUBLE PRECISION NOT NULL DEFAULT 0;
